[package]
name = "rcomp"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "rcomp"
path = "src/main.rs"

[features]
default = ["rar"]
rar = ["rcomp-core/rar"]

[dependencies]
rcomp-core = { path = "../rcomp-core", version = "0.3.0" }
clap.workspace = true
anyhow.workspace = true
ctrlc.workspace = true
indicatif.workspace = true
clap_complete.workspace = true
clap_mangen.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true
