[workspace]
members = ["crates/*", "apps/rcomp-desktop/src-tauri"]
default-members = ["crates/rcomp-core", "crates/rcomp"]
resolver = "3"

[workspace.package]
version = "0.3.1"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Unified compression/archive library and CLI"
readme = "README.md"
keywords = ["compression", "archive", "zip", "tar", "zstd"]
categories = ["compression", "command-line-utilities"]

[workspace.dependencies]
ctrlc = "3"
thiserror = "2"
tempfile = "3"
flate2 = "1.1.9"
bzip2 = "0.6.1"
liblzma = { version = "0.4.6", features = ["parallel"] }
zstd = { version = "0.13.3", features = ["zstdmt"] }
lz4 = "1.28.1"
brotli = "8.0.3"
tar = "0.4.46"
zip = "8.6.0"
filetime = "0.2"
sevenz-rust2 = "0.21.0"
unrar = "0.5.8"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
indicatif = "0.18"
clap_complete = "4"
clap_mangen = "0.3"
assert_cmd = "2"
predicates = "3"
ignore = "0.4"
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
